## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
codecov: true
coveralls: true
os:
  - linux
  - osx

julia:
  - 1.0
  - 1.1
  - 1.2
  - nightly

matrix:
  allow_failures:
  - julia: nightly

notifications:
  email: false
sudo: false
addons:
  apt_packages:
    - gfortran

jobs:
  include:
    - stage: "Testing"
      julia: 1.0
      os: linux
      script:
        - julia --project=test/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=test/ --code-coverage test/runtests.jl
      after_success: skip
after_success:
    - julia -e 'using Pkg; Pkg.add("Coverage")'
    - julia -e 'using Coverage; Codecov.submit(process_folder())'
