## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  #- osx

julia:
  - 1.1
#  - 1.2
#  - nightly

#matrix:
#  allow_failures:
#  - julia: nightly

notifications:
  email: false

addons:
  apt_packages:
    - gfortran

after_success:
- julia -e 'using Pkg; cd(Pkg.dir("EAGO")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'   # push coverage results to Coveralls
- julia -e 'using Pkg; cd(Pkg.dir("EAGO")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'        # push coverage results to Codecov
