## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
codecov: true
coveralls: true

sudo: required

services:
  - docker

os:
  - linux
  - osx    #build never started in travis CI, will trouble shoot later

julia:
  #- 0.7 disabled to speed up CI tests
  - 1.1
  - 1.2
  - nightly #disabled to speed up CI tests

notifications:
  email: false

git:
  depth: 99999999

matrix:
  allow_failures:
  - julia: nightly

addons:
  apt_packages:
    - gfortran
