language: julia
codecov: true
coveralls: true

sudo: required

os:
  - linux
  #- osx

julia:
  - 1.2
  - 1.3
  - 1.4
  - nightly

matrix:
  allow_failures:
  - julia: 1.4
  - julia: nightly

#env:
#  global:
#    - DOCUMENTER_DEBUG=true

notifications:
  email: false

addons:
  apt_packages:
    - gfortran

#jobs:
  #include:
  #  - stage: "Documentation"
  #    julia: 1.0
  #    os: linux
  #    script:
  #      - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
  #                                             Pkg.instantiate()'
  #      - julia --project=docs/ docs/make.jl
  #    after_success: skip
